#!/bin/sh
[ "$1" ] || exit 1
stty -echo
printf 'Enter your password: '
read pass
printf '\nEnter your password again: '
read pass2
printf '\n'
stty echo
[ "$pass" = "$pass2" ] && { printf '%s' "$pass" | pm a "$1" ;} || {
    printf "Passwords don't match\n"
    exit 1
}
