#!/usr/bin/env sh

# POSIX compliant version of Dave Eddy's
# zzz-user-hooks.

out() { printf '\033[1;36m-> \033[m%s\n' "$@" ;}
error() { printf '\033[1;31m-> \033[mError: %s\n' "$@" >&2 ;}
die() { error "$1" ; exit 1 ;}

for sock in /tmp/.X11-unix/X* ; do
	uid=$(stat -t "$sock" | cut -d ' ' -f 6)
	user="$(grep ":$uid:" /etc/passwd | cut -d ':' -f 1)"
	[ "$user" ] || die "User of $sock could not be found"
	display=":${sock##*X}"
done

home="$(grep ":$uid:" /etc/passwd | cut -d ':' -f 6 )"
[ "$home" ] && [ -d "$home" ] || die "Could not find user's home directory"
env="DISPLAY=$display"
[ -e "$home/.Xauthority" ] && env="$env XAUTHORITY=$home/.Xauthority" || error "Could not find user's Xauthority file"

case ${0##*/} in 
	99-onresume) out "Running $home/.onresume" ; su -c "$env $home/.onresume" "$user" ;;
	99-onsuspend) out "Running $home/.onsuspend" ; su -c "$env $home/.onsuspend" "$user" ;;
esac
