#!/bin/sh
# shellcheck disable=2015

# POSIX compliant version of Dave Eddy's
# zzz-user-hooks.

out() { printf '\033[1;36m-> \033[m%s\n' "$@" ;}
error() { printf '\033[1;31m-> \033[mError: %s\n' "$@" >&2 ;}
die() { error "$1" ; exit 1 ;}
getent_passwd() {
    while read -r line; do
        case "$line" in $1:*|*:*:$1:*:*:*:*) printf '%s\n' "$line"; return 0; esac
    done < /etc/passwd
}

for sock in /tmp/.X11-unix/X* ; do
    set -- $(ls -ld "$sock")
    ent=$(getent_passwd "${3:-root}")
    user=${ent%%:*}
    [ "$user" ] || die "User of $sock could not be found"
    display=":${sock##*X}"
done

home=${ent%:*} home=${home##*:}
[ -d "$home" ] || die "Could not find user's home directory"
env="DISPLAY=$display"

[ -e "$home/.Xauthority" ] && env="$env XAUTHORITY=$home/.Xauthority" ||
    error "Could not find user's Xauthority file"

out "Running $home/.${0##*-}"
su -c "$env $home/.${0##*-}" "$user"
