#!/bin/sh

# KISS functions that I use. Mostly
# for repository management.

out() { printf '\033[1;36m-> \033[m%s\n' "$@" ;}
error() { printf '\033[1;31m!> error: \033[m%s\n' "$@" >&2 ;}
die() { error "$1" ; exit 1 ;}

usage() {
out \
"${0##*/} [a|b|n|u|h] [options]" \
"add    Commit the current directory as a new package" \
"bump   Commit current directory with a 'package: bump to version message'" \
"help   Print help information per function" \
"new    Create a template package with package-name, version, and source" \
"update Update a package with the given version number"
exit 1
}

help() {
    case "$1" in
        a|add) out "Resets git, adds current directory and commits" "with a 'package: add new package at version to repository' message" ; exit ;;
        b|bump) out "Resets git, adds current directory and commits" "with a 'package: bump to version' message"; exit ;;
        n|new) out "kf new <package> [version] [sources]"; exit ;;
        u|update) out "Tries to update a package version with basic sed" ; exit ;;
        h|help) out "kf help <function>" ; exit ;;
        *) usage ;; esac
}

add() {
    [ "$1" ] && help add
    [ -f version ] || die "Could not find version directory, are you sure that you are on a package directory?"
    git reset
    git add .
    git commit -m "$(basename "$PWD"): add new package at $(cut -d ' ' -f 1 version) to $(basename "$(dirname "$PWD")")"
}

bump() {
    [ "$1" ] && help bump
    [ -f version ] || die "Could not find version directory, are you sure that you are on a package directory?"
    git reset
    git add .
    git commit -m "$(basename "$PWD"): bump to $(cut -d ' ' -f 1 version)"
}

new() {
    # 1: Package name
    # 2: Package version
    # 3: Package source
    [ "$1" ] || help new
    [ -d "$1" ] && die "Package $1 already exists"
    mkdir -p "$1" || die "Couldn't create directory to ${PWD}/${1}"
    out "Populating build file"; {
        printf "#!/bin/sh -e\n" > "$1/build"
	chmod +x "$1/build"
    }
    [ "$2" ] && {
        out "Populating version file with '${2%% *} 1'"
        printf '%s 1\n' "${2%% *}" > "$1/version"
    } || printf " 1\n" > "$1/version"

    [ "$3" ] && {
        out "Populating sources file with '$3'"
        printf '%s\n' "$3" > "$1/sources"
    } || :> "$1/sources"
}

update() {
    case "$1" in --help|help|-h) help update ;; esac
    [ "$1" ] || help update
    pkg="${PWD##*/}"
    [ -f version ] || die "Could not find version file, are you sure that you are on a package directory?"
    read -r ver _ < version
    for file in sources version ; do out "$file" ; sed "s/$ver/$1/g" "$file" ; done
    out "Is this correct?" "Press CTRL+C to cancel"
    read -r _
    sed -i "s/$ver/$1/g" sources version
    out "Should I (c)hecksum, (b)uild, (i)nstall?"
    read ans
    case "$ans" in c) kiss c "$pkg" ;; b) kiss c "$pkg" && kiss b "$pkg" ;; i) kiss c "$pkg" && kiss b "$pkg" && kiss i "$pkg" ;; esac
}


mode="$1"
shift

case "$mode" in
    a|add)  add "$@" ;;
    b|bump) bump "$@" ;;
    n|new) new "$@" ;;
    u|update) update "$@" ;;
    h|help) help "$1" ;;
    *) usage ;;
esac
