#!/bin/sh
#
# kiss-reporevdepends - Display packages which depend on package.

[ "$1" ] || {
    printf 'usage: %s <pkg>\n' "${0##*/}"
    exit 1
}

for repo in $(echo "$KISS_PATH" | tr ':' ' ') ; do
    cd "$repo/.." ||:
    # Use a simple 'grep' to display packages depending on '$1'.
    grep "^$1" -- "${repo##*/}"/*/depends 2>/dev/null ||:
done
