#!/bin/sh
# nap - not the full zzz, but a light one

[ "$1" ] && { printf 'Usage: %s\nThere are not many options when taking a nap.\n' "${0##*/}" ; exit 1 ;}
grep -q mem /sys/power/state || { printf "Suspend not supported.\n"; exit 1 ;}
test -w /sys/power/state || { printf "Sleep permission denied.\n" ; exit 1 ;}
for hook in /etc/zzz.d/suspend/* ; do
    [ -x "$hook" ] && "$hook"
done
printf mem >/sys/power/state || { printf "Could not suspend.\n" ; exit 1 ;}
for hook in /etc/zzz.d/resume/*; do
    [ -x "$hook" ] && "$hook"
done
